#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: 5424026
#
Name     : compose
Version  : 2.32.2
Release  : 4
URL      : https://github.com/docker/compose/archive/refs/tags/v2.32.2.tar.gz
Source0  : https://github.com/docker/compose/archive/refs/tags/v2.32.2.tar.gz
Source1  : http://localhost/cgit/projects/compose-vendor/snapshot/compose-vendor-2.32.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-SA-4.0 ISC MIT MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: compose-bin = %{version}-%{release}
Requires: compose-license = %{version}-%{release}
BuildRequires : go
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Table of Contents
- [Docker Compose v2](#docker-compose-v2)
- [Where to get Docker Compose](#where-to-get-docker-compose)
+ [Windows and macOS](#windows-and-macos)
+ [Linux](#linux)
- [Quick Start](#quick-start)
- [Contributing](#contributing)
- [Legacy](#legacy)
# Docker Compose v2

%package bin
Summary: bin components for the compose package.
Group: Binaries
Requires: compose-license = %{version}-%{release}

%description bin
bin components for the compose package.


%package license
Summary: license components for the compose package.
Group: Default

%description license
license components for the compose package.


%prep
%setup -q -n compose-2.32.2
cd %{_builddir}
tar xf %{_sourcedir}/compose-vendor-2.32.2.tar.xz
cd %{_builddir}/compose-2.32.2
mkdir -p ./
cp -r %{_builddir}/compose-vendor-2.32.2/* %{_builddir}/compose-2.32.2/./

%build
## build_prepend content
unset CLEAR_DEBUG_TERSE
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736468728
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  -f Makefile GOFLAGS='-mod=vendor -buildmode=pie -v'


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736468728
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compose
cp %{_builddir}/compose-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/compose/1128f8f91104ba9ef98d37eea6523a888dcfa5de || :
cp %{_builddir}/compose-vendor-%{version}/vendor/dario.cat/mergo/LICENSE %{buildroot}/usr/share/package-licenses/compose/eecfc0c7e0930c6ba1ed0ff2d46a0a6fa0d16d6c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/AdaLogics/go-fuzz-headers/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/AlecAivazis/survey/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/c712a6f5c083360e03f0be6be5e883c1b8438984 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/AlecAivazis/survey/v2/terminal/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/7f45f6163bb54449d503978cff7537f6a468f1b1 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/compose/836ef1b46953afdb78ce3929bc6831ca83620b65 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/Masterminds/semver/v3/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/020acfcf6d6bd6d701d19bd16f49d0bf18441779 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/Microsoft/go-winio/LICENSE %{buildroot}/usr/share/package-licenses/compose/11a8fec351554e8f6c3f4dac5a1f4049dd467ba8 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/acarl005/stripansi/LICENSE %{buildroot}/usr/share/package-licenses/compose/c5f9a33906e2c8c9b408c50d38e01e7a08449ee7 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/config/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/credentials/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/internal/ini/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/internal/sync/singleflight/LICENSE %{buildroot}/usr/share/package-licenses/compose/6c51f59590222932ec338ecc2f82da24eaaabf0d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/service/sso/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/service/ssooidc/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/aws-sdk-go-v2/service/sts/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/smithy-go/LICENSE %{buildroot}/usr/share/package-licenses/compose/57aed0b0f74e63f6b85cce11bce29ba1710b422b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/aws/smithy-go/internal/sync/singleflight/LICENSE %{buildroot}/usr/share/package-licenses/compose/6c51f59590222932ec338ecc2f82da24eaaabf0d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/beorn7/perks/LICENSE %{buildroot}/usr/share/package-licenses/compose/b2e4520feb0f9b51ad373256b94c3faf4c1e6871 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/buger/goterm/LICENSE %{buildroot}/usr/share/package-licenses/compose/c58c331bb2225ba2c11040abafd1f41e11476661 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/cenkalti/backoff/v4/LICENSE %{buildroot}/usr/share/package-licenses/compose/101c182fa18fd56a09164278f17e4282264c5e9e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/cespare/xxhash/v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/7be82c1a81e7197640a88df91dc82d64b77c7acd || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/compose-spec/compose-go/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/878e7d86573d6c8ff65d2eaab294734b3f4d3d81 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/compose-spec/compose-go/v2/dotenv/LICENSE %{buildroot}/usr/share/package-licenses/compose/6d5bc87a78c5e4ba18c80e7c739efaafae7d26e9 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/console/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/containerd/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/containerd/api/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/continuity/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/errdefs/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/log/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/platforms/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/ttrpc/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/containerd/typeurl/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/cpuguy83/go-md2man/v2/LICENSE.md %{buildroot}/usr/share/package-licenses/compose/b7a606730713ac061594edab33cf941704b4a95c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/compose/d2f340a01dd48b589a70f627cf7058c585a315e4 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/distribution/reference/LICENSE %{buildroot}/usr/share/package-licenses/compose/c700a8b9312d24bdc57570f7d6a131cf63d89016 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/buildx/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/cli-docs-tool/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/cli/LICENSE %{buildroot}/usr/share/package-licenses/compose/878e7d86573d6c8ff65d2eaab294734b3f4d3d81 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/distribution/LICENSE %{buildroot}/usr/share/package-licenses/compose/c700a8b9312d24bdc57570f7d6a131cf63d89016 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/docker-credential-helpers/LICENSE %{buildroot}/usr/share/package-licenses/compose/f3eab54cb1736b419ef75b8c44bea2b17614bd31 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/compose/20b06a68cf65738d43afa04acce0126f341c77f8 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/compose/5476f2f91673ef040f1956907e7f45e72d5e11ee || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/go-connections/LICENSE %{buildroot}/usr/share/package-licenses/compose/3110e55750143a84918d7423febc9c83a55bc28c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/go-metrics/LICENSE %{buildroot}/usr/share/package-licenses/compose/376caa2cd54c4196280157d071524614350e7ce8 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/go-metrics/LICENSE.docs %{buildroot}/usr/share/package-licenses/compose/979fd7d5c67073b265d96f584aac3de1c419b8e2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/go-units/LICENSE %{buildroot}/usr/share/package-licenses/compose/3110e55750143a84918d7423febc9c83a55bc28c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/docker/go/LICENSE %{buildroot}/usr/share/package-licenses/compose/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/emicklei/go-restful/v3/LICENSE %{buildroot}/usr/share/package-licenses/compose/a8993f4a51771a0333dbbc5b1c4395a2ccaa4d9f || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/felixge/httpsnoop/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/d3d30f733d36ea721eb89e9c37f899f729a0ea5e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/fvbommel/sortorder/LICENSE %{buildroot}/usr/share/package-licenses/compose/8a40bfb169d0050621b1dc706311e3fd62ec65eb || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/go-logr/logr/LICENSE %{buildroot}/usr/share/package-licenses/compose/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/go-logr/stdr/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/go-openapi/jsonpointer/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/go-openapi/jsonreference/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/go-openapi/swag/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/go-viper/mapstructure/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/5ad2002bc8d2b22e2034867d159f71ba6258e18f || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/gofrs/flock/LICENSE %{buildroot}/usr/share/package-licenses/compose/dc2d3356b48d68245a75cc2dcbfd1881d413920f || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/compose/06b27345acae9303e13dde9974d2b2e318b05989 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/compose/aa9b240f558caed367795f667629ccbca28f20b2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/google/gnostic-models/LICENSE %{buildroot}/usr/share/package-licenses/compose/5a7d7df655ba40478fae80a6abafc6afc36f9b6a || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/google/go-cmp/LICENSE %{buildroot}/usr/share/package-licenses/compose/7080652cc78cd9855d39e324529a3b5f3745dcd6 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/google/gofuzz/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/google/shlex/COPYING %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/google/uuid/LICENSE %{buildroot}/usr/share/package-licenses/compose/08021ae73f58f423dd6e7b525e81cf2520f7619e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/gorilla/mux/LICENSE %{buildroot}/usr/share/package-licenses/compose/3bf9ba7c00d68e0aef9424055f96cc8d123afad8 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/gorilla/websocket/LICENSE %{buildroot}/usr/share/package-licenses/compose/307711a68aa375a23d90191db6f720426cf88402 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/c2add16c875ec7abad9c453d0a0c325dc814e8f2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/hashicorp/errwrap/LICENSE %{buildroot}/usr/share/package-licenses/compose/523489384296f403da31edf8edf6f9023d328517 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/hashicorp/go-cleanhttp/LICENSE %{buildroot}/usr/share/package-licenses/compose/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/hashicorp/go-multierror/LICENSE %{buildroot}/usr/share/package-licenses/compose/2ebe302ef4d8d257ac6f0a916285b51937a25641 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/imdario/mergo/LICENSE %{buildroot}/usr/share/package-licenses/compose/eecfc0c7e0930c6ba1ed0ff2d46a0a6fa0d16d6c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/in-toto/in-toto-golang/LICENSE %{buildroot}/usr/share/package-licenses/compose/4bdbde42627d27581d2ea6f4e6fd2de18b1d2303 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/inconshreveable/mousetrap/LICENSE %{buildroot}/usr/share/package-licenses/compose/62446e71c226403f1a2e67d0f66ede03e3fbdd2f || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/jonboulle/clockwork/LICENSE %{buildroot}/usr/share/package-licenses/compose/92a74693f02c8e78dd90b2014c52bc35a95bab86 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/josharian/intern/license.md %{buildroot}/usr/share/package-licenses/compose/8b31eebf3b5472b746a3a34142877b3bb6bd8e68 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/json-iterator/go/LICENSE %{buildroot}/usr/share/package-licenses/compose/810612ee8c1872b7ee4dba34c090ebd8f7491aa1 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/kballard/go-shellquote/LICENSE %{buildroot}/usr/share/package-licenses/compose/3afc456546a3fa3e82c0d21844cd9911d7d4464b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/klauspost/compress/LICENSE %{buildroot}/usr/share/package-licenses/compose/0e8f2042647b8140e79c4eb7d233d1b39231db09 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/klauspost/compress/internal/snapref/LICENSE %{buildroot}/usr/share/package-licenses/compose/b7b97d84a5f0b778ab971d2afce44f47c8b6e80a || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/7be82c1a81e7197640a88df91dc82d64b77c7acd || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mailru/easyjson/LICENSE %{buildroot}/usr/share/package-licenses/compose/554fb441fbb1607579b7c9f8e9d7fab5d00e3a51 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mattn/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/compose/5ca808f075931c5322193d4afd5a3370c824f810 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mattn/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/compose/5b53018d7f0706e49275a92d36b54cfbfbb71367 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mattn/go-runewidth/LICENSE %{buildroot}/usr/share/package-licenses/compose/5ca808f075931c5322193d4afd5a3370c824f810 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mattn/go-shellwords/LICENSE %{buildroot}/usr/share/package-licenses/compose/f7f33fde14de785a3ac53f250bb746ba30844639 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mgutz/ansi/LICENSE %{buildroot}/usr/share/package-licenses/compose/69bd14555bdab2001efa07a655af9def7438e017 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/miekg/pkcs11/LICENSE %{buildroot}/usr/share/package-licenses/compose/a347f428584b1ae13a669c007351ba7885597d59 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mitchellh/go-ps/LICENSE.md %{buildroot}/usr/share/package-licenses/compose/d676a57141ac47c27699fc8b03e1a2e59abb96ef || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mitchellh/hashstructure/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/5e532746c55cbcc078e80cff9c6c532db022f7b2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mitchellh/mapstructure/LICENSE %{buildroot}/usr/share/package-licenses/compose/5ad2002bc8d2b22e2034867d159f71ba6258e18f || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/buildkit/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/docker-image-spec/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/locker/LICENSE %{buildroot}/usr/share/package-licenses/compose/600a7a38fdb246fd62c4e101868e6d0da9a3843c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/patternmatcher/LICENSE %{buildroot}/usr/share/package-licenses/compose/20b06a68cf65738d43afa04acce0126f341c77f8 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/spdystream/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/mountinfo/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/sequential/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/signal/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/symlink/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/compose/de6aabbb551ff752e690d7a1136a5b5228f130cb || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/compose/818cd8d3934fc2af85e81c1f39c51ef7f661c139 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/user/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/sys/userns/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/moby/term/LICENSE %{buildroot}/usr/share/package-licenses/compose/20b06a68cf65738d43afa04acce0126f341c77f8 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/modern-go/concurrent/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/modern-go/reflect2/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/morikuni/aec/LICENSE %{buildroot}/usr/share/package-licenses/compose/3faf341fbc32621fe1ac089ae2ab7a23980fc189 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/munnerz/goautoneg/LICENSE %{buildroot}/usr/share/package-licenses/compose/3486abfdd66d1bd30f9edeeb779a7f04d043d457 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/mxk/go-flowrate/LICENSE %{buildroot}/usr/share/package-licenses/compose/43caeb543b78e31d617e7b7e6e5d156a79f8da30 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/opencontainers/go-digest/LICENSE %{buildroot}/usr/share/package-licenses/compose/93ac97c9679b68518f1fd7de627ce2f77f44082d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/opencontainers/go-digest/LICENSE.docs %{buildroot}/usr/share/package-licenses/compose/979fd7d5c67073b265d96f584aac3de1c419b8e2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/opencontainers/image-spec/LICENSE %{buildroot}/usr/share/package-licenses/compose/298850a6cdb155f54cfa44641df70b36228ed031 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/otiai10/copy/LICENSE %{buildroot}/usr/share/package-licenses/compose/ba376710df69a5603facdf037075e8c17581ef47 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/pelletier/go-toml/LICENSE %{buildroot}/usr/share/package-licenses/compose/0f506ab42c27323e32b4c8baa57cf7ddfc8d1b78 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/compose/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/planetscale/vtprotobuf/LICENSE %{buildroot}/usr/share/package-licenses/compose/65a1dc21258a9af817abad878dceb245e74540f7 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/compose/cd3e4d932cee20da681e6b3bee8139cb4f734034 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/prometheus/client_golang/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/prometheus/client_golang/internal/github.com/golang/gddo/LICENSE %{buildroot}/usr/share/package-licenses/compose/98bd4176f4779516009b9effebe10231c836470d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/prometheus/client_model/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/prometheus/common/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/prometheus/procfs/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/r3labs/sse/LICENSE %{buildroot}/usr/share/package-licenses/compose/d22157abc0fc0b4ae96380c09528e23cf77290a9 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/rivo/uniseg/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/f60d047cd34de4c91b3a045ebf117fe54b3c279e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/russross/blackfriday/v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/da34754c05d40ff81f91de8c1b85ea6e5503e21d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/secure-systems-lab/go-securesystemslib/LICENSE %{buildroot}/usr/share/package-licenses/compose/41df43abd14c5aded4e3e8f0f68e595c4585627c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/serialx/hashring/LICENSE %{buildroot}/usr/share/package-licenses/compose/54f444f1914b8c04a43c6f82c1defa95d13952a7 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/shibumi/go-pathspec/GO-LICENSE %{buildroot}/usr/share/package-licenses/compose/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/shibumi/go-pathspec/LICENSE %{buildroot}/usr/share/package-licenses/compose/92a74693f02c8e78dd90b2014c52bc35a95bab86 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/compose/a1c7852c717fed2c9a0284ed112ea66013230da6 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/skratchdot/open-golang/LICENSE %{buildroot}/usr/share/package-licenses/compose/a25a6744be0a23436014541afd340d2f2aa1e46c || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/package-licenses/compose/c7feacb4667f8c63c89e2eeeb9a913bd3ced8ac2 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/compose/b3c86ae465b21f7323059db335158b48187731c7 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/compose/892204393ca075d09c8b1c1d880aba1ae0a2b805 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/theupdateframework/notary/LICENSE %{buildroot}/usr/share/package-licenses/compose/56914ae6f6cdf4b25c01b1af2fb1622b8f7796e4 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/theupdateframework/notary/tuf/LICENSE %{buildroot}/usr/share/package-licenses/compose/5f7cbb4c5d5541ee1f07f4ca37c98b9ae441ada7 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/tilt-dev/fsnotify/LICENSE %{buildroot}/usr/share/package-licenses/compose/66a9502ecba0bae239ca6ba2c3e8a2fe5558a893 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/tonistiigi/fsutil/LICENSE %{buildroot}/usr/share/package-licenses/compose/f3a0255a9eb8e1668b0f178781487e9537df3071 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/tonistiigi/go-csvvalue/LICENSE %{buildroot}/usr/share/package-licenses/compose/4f352dcb8813f2bd2709c59a3f398d8e56ac54fc || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/tonistiigi/units/LICENSE %{buildroot}/usr/share/package-licenses/compose/999844f0a50861238f93a4cbbb9191b778d17730 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/tonistiigi/vt100/LICENSE %{buildroot}/usr/share/package-licenses/compose/c93b34f7b1daa3cce0988a6cc7140c9403de319d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/compose/b7173385030ef97bce57b5b4b78b48763c83aed3 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/compose/b7173385030ef97bce57b5b4b78b48763c83aed3 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/compose/b7173385030ef97bce57b5b4b78b48763c83aed3 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/metric/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/sdk/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/sdk/metric/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/otel/trace/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.opentelemetry.io/proto/otlp/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.uber.org/goleak/LICENSE %{buildroot}/usr/share/package-licenses/compose/760abad46150e115fd60080bcf69ebc2b12a044e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/go.uber.org/mock/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/exp/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/oauth2/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/sync/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/term/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/golang.org/x/time/LICENSE %{buildroot}/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/google.golang.org/genproto/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/google.golang.org/genproto/googleapis/api/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/google.golang.org/genproto/googleapis/rpc/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/google.golang.org/grpc/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/google.golang.org/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/compose/74850a25a5319bdddc0d998eb8926c18bada282b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/cenkalti/backoff.v1/LICENSE %{buildroot}/usr/share/package-licenses/compose/101c182fa18fd56a09164278f17e4282264c5e9e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/inf.v0/LICENSE %{buildroot}/usr/share/package-licenses/compose/580c0a1f1386fe13bce395d23bdaf3b14ae2e20b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/compose/ad00ce7340d89dc13ccc59920ef75cb55af5b164 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/yaml.v2/NOTICE %{buildroot}/usr/share/package-licenses/compose/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/yaml.v3/LICENSE %{buildroot}/usr/share/package-licenses/compose/b74b3b31bc15ad5e94fc1947d682aa3d84132fce || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gopkg.in/yaml.v3/NOTICE %{buildroot}/usr/share/package-licenses/compose/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gotest.tools/v3/LICENSE %{buildroot}/usr/share/package-licenses/compose/c3001aa5b380f41731de929c562043693d7eb1ca || :
cp %{_builddir}/compose-vendor-%{version}/vendor/gotest.tools/v3/internal/difflib/LICENSE %{buildroot}/usr/share/package-licenses/compose/cd3e4d932cee20da681e6b3bee8139cb4f734034 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE %{buildroot}/usr/share/package-licenses/compose/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/klog/v2/LICENSE %{buildroot}/usr/share/package-licenses/compose/172ca3bbafe312a1cf09cfff26953db2f425c28e || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/kube-openapi/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/LICENSE %{buildroot}/usr/share/package-licenses/compose/6c1c86ffff267e1d7d8f03dca1c41492e62f265b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/kube-openapi/pkg/validation/spec/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/kube-openapi/pkg/validation/spec/license.go %{buildroot}/usr/share/package-licenses/compose/555e9ac61d94352b3c2935e77b51fc6dc31d4822 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/utils/LICENSE %{buildroot}/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compose-vendor-%{version}/vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE %{buildroot}/usr/share/package-licenses/compose/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b || :
cp %{_builddir}/compose-vendor-%{version}/vendor/sigs.k8s.io/json/LICENSE %{buildroot}/usr/share/package-licenses/compose/1fec85ad53bebf4bffc9cf02a7dfcfa56ad6b94d || :
cp %{_builddir}/compose-vendor-%{version}/vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE %{buildroot}/usr/share/package-licenses/compose/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/compose-vendor-%{version}/vendor/sigs.k8s.io/yaml/LICENSE %{buildroot}/usr/share/package-licenses/compose/271aeaf56ee621c5accfc2a9db0b10717e038eaf || :
cp %{_builddir}/compose-vendor-%{version}/vendor/tags.cncf.io/container-device-interface/LICENSE %{buildroot}/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
export GOAMD64=v2
GOAMD64=v2
true
## install_append content
install -d %{buildroot}/usr/bin/
install -m0755 bin/build/docker-compose %{buildroot}/usr/bin/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/docker-compose

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compose/020acfcf6d6bd6d701d19bd16f49d0bf18441779
/usr/share/package-licenses/compose/06b27345acae9303e13dde9974d2b2e318b05989
/usr/share/package-licenses/compose/08021ae73f58f423dd6e7b525e81cf2520f7619e
/usr/share/package-licenses/compose/0e8f2042647b8140e79c4eb7d233d1b39231db09
/usr/share/package-licenses/compose/0f506ab42c27323e32b4c8baa57cf7ddfc8d1b78
/usr/share/package-licenses/compose/101c182fa18fd56a09164278f17e4282264c5e9e
/usr/share/package-licenses/compose/1128f8f91104ba9ef98d37eea6523a888dcfa5de
/usr/share/package-licenses/compose/11a8fec351554e8f6c3f4dac5a1f4049dd467ba8
/usr/share/package-licenses/compose/172ca3bbafe312a1cf09cfff26953db2f425c28e
/usr/share/package-licenses/compose/1fec85ad53bebf4bffc9cf02a7dfcfa56ad6b94d
/usr/share/package-licenses/compose/20b06a68cf65738d43afa04acce0126f341c77f8
/usr/share/package-licenses/compose/271aeaf56ee621c5accfc2a9db0b10717e038eaf
/usr/share/package-licenses/compose/298850a6cdb155f54cfa44641df70b36228ed031
/usr/share/package-licenses/compose/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/compose/2ebe302ef4d8d257ac6f0a916285b51937a25641
/usr/share/package-licenses/compose/307711a68aa375a23d90191db6f720426cf88402
/usr/share/package-licenses/compose/3110e55750143a84918d7423febc9c83a55bc28c
/usr/share/package-licenses/compose/3486abfdd66d1bd30f9edeeb779a7f04d043d457
/usr/share/package-licenses/compose/35ca00c1c9042b449d2d9b16234307841fe3a411
/usr/share/package-licenses/compose/376caa2cd54c4196280157d071524614350e7ce8
/usr/share/package-licenses/compose/3afc456546a3fa3e82c0d21844cd9911d7d4464b
/usr/share/package-licenses/compose/3bf9ba7c00d68e0aef9424055f96cc8d123afad8
/usr/share/package-licenses/compose/3faf341fbc32621fe1ac089ae2ab7a23980fc189
/usr/share/package-licenses/compose/41df43abd14c5aded4e3e8f0f68e595c4585627c
/usr/share/package-licenses/compose/43caeb543b78e31d617e7b7e6e5d156a79f8da30
/usr/share/package-licenses/compose/4bdbde42627d27581d2ea6f4e6fd2de18b1d2303
/usr/share/package-licenses/compose/4f352dcb8813f2bd2709c59a3f398d8e56ac54fc
/usr/share/package-licenses/compose/523489384296f403da31edf8edf6f9023d328517
/usr/share/package-licenses/compose/5476f2f91673ef040f1956907e7f45e72d5e11ee
/usr/share/package-licenses/compose/54f444f1914b8c04a43c6f82c1defa95d13952a7
/usr/share/package-licenses/compose/554fb441fbb1607579b7c9f8e9d7fab5d00e3a51
/usr/share/package-licenses/compose/555e9ac61d94352b3c2935e77b51fc6dc31d4822
/usr/share/package-licenses/compose/56914ae6f6cdf4b25c01b1af2fb1622b8f7796e4
/usr/share/package-licenses/compose/57aed0b0f74e63f6b85cce11bce29ba1710b422b
/usr/share/package-licenses/compose/580c0a1f1386fe13bce395d23bdaf3b14ae2e20b
/usr/share/package-licenses/compose/5a7d7df655ba40478fae80a6abafc6afc36f9b6a
/usr/share/package-licenses/compose/5ad2002bc8d2b22e2034867d159f71ba6258e18f
/usr/share/package-licenses/compose/5b53018d7f0706e49275a92d36b54cfbfbb71367
/usr/share/package-licenses/compose/5ca808f075931c5322193d4afd5a3370c824f810
/usr/share/package-licenses/compose/5e532746c55cbcc078e80cff9c6c532db022f7b2
/usr/share/package-licenses/compose/5f7cbb4c5d5541ee1f07f4ca37c98b9ae441ada7
/usr/share/package-licenses/compose/600a7a38fdb246fd62c4e101868e6d0da9a3843c
/usr/share/package-licenses/compose/62446e71c226403f1a2e67d0f66ede03e3fbdd2f
/usr/share/package-licenses/compose/65a1dc21258a9af817abad878dceb245e74540f7
/usr/share/package-licenses/compose/66a9502ecba0bae239ca6ba2c3e8a2fe5558a893
/usr/share/package-licenses/compose/69bd14555bdab2001efa07a655af9def7438e017
/usr/share/package-licenses/compose/6c1c86ffff267e1d7d8f03dca1c41492e62f265b
/usr/share/package-licenses/compose/6c51f59590222932ec338ecc2f82da24eaaabf0d
/usr/share/package-licenses/compose/6d5bc87a78c5e4ba18c80e7c739efaafae7d26e9
/usr/share/package-licenses/compose/7080652cc78cd9855d39e324529a3b5f3745dcd6
/usr/share/package-licenses/compose/74850a25a5319bdddc0d998eb8926c18bada282b
/usr/share/package-licenses/compose/760abad46150e115fd60080bcf69ebc2b12a044e
/usr/share/package-licenses/compose/7be82c1a81e7197640a88df91dc82d64b77c7acd
/usr/share/package-licenses/compose/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/compose/7f45f6163bb54449d503978cff7537f6a468f1b1
/usr/share/package-licenses/compose/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b
/usr/share/package-licenses/compose/810612ee8c1872b7ee4dba34c090ebd8f7491aa1
/usr/share/package-licenses/compose/818cd8d3934fc2af85e81c1f39c51ef7f661c139
/usr/share/package-licenses/compose/836ef1b46953afdb78ce3929bc6831ca83620b65
/usr/share/package-licenses/compose/878e7d86573d6c8ff65d2eaab294734b3f4d3d81
/usr/share/package-licenses/compose/892204393ca075d09c8b1c1d880aba1ae0a2b805
/usr/share/package-licenses/compose/8a40bfb169d0050621b1dc706311e3fd62ec65eb
/usr/share/package-licenses/compose/8b31eebf3b5472b746a3a34142877b3bb6bd8e68
/usr/share/package-licenses/compose/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/compose/92a74693f02c8e78dd90b2014c52bc35a95bab86
/usr/share/package-licenses/compose/93ac97c9679b68518f1fd7de627ce2f77f44082d
/usr/share/package-licenses/compose/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
/usr/share/package-licenses/compose/979fd7d5c67073b265d96f584aac3de1c419b8e2
/usr/share/package-licenses/compose/98bd4176f4779516009b9effebe10231c836470d
/usr/share/package-licenses/compose/999844f0a50861238f93a4cbbb9191b778d17730
/usr/share/package-licenses/compose/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc
/usr/share/package-licenses/compose/a1c7852c717fed2c9a0284ed112ea66013230da6
/usr/share/package-licenses/compose/a25a6744be0a23436014541afd340d2f2aa1e46c
/usr/share/package-licenses/compose/a347f428584b1ae13a669c007351ba7885597d59
/usr/share/package-licenses/compose/a8993f4a51771a0333dbbc5b1c4395a2ccaa4d9f
/usr/share/package-licenses/compose/aa9b240f558caed367795f667629ccbca28f20b2
/usr/share/package-licenses/compose/ad00ce7340d89dc13ccc59920ef75cb55af5b164
/usr/share/package-licenses/compose/b2e4520feb0f9b51ad373256b94c3faf4c1e6871
/usr/share/package-licenses/compose/b3c86ae465b21f7323059db335158b48187731c7
/usr/share/package-licenses/compose/b7173385030ef97bce57b5b4b78b48763c83aed3
/usr/share/package-licenses/compose/b74b3b31bc15ad5e94fc1947d682aa3d84132fce
/usr/share/package-licenses/compose/b7a606730713ac061594edab33cf941704b4a95c
/usr/share/package-licenses/compose/b7b97d84a5f0b778ab971d2afce44f47c8b6e80a
/usr/share/package-licenses/compose/ba376710df69a5603facdf037075e8c17581ef47
/usr/share/package-licenses/compose/c2add16c875ec7abad9c453d0a0c325dc814e8f2
/usr/share/package-licenses/compose/c3001aa5b380f41731de929c562043693d7eb1ca
/usr/share/package-licenses/compose/c58c331bb2225ba2c11040abafd1f41e11476661
/usr/share/package-licenses/compose/c5f9a33906e2c8c9b408c50d38e01e7a08449ee7
/usr/share/package-licenses/compose/c700a8b9312d24bdc57570f7d6a131cf63d89016
/usr/share/package-licenses/compose/c712a6f5c083360e03f0be6be5e883c1b8438984
/usr/share/package-licenses/compose/c7feacb4667f8c63c89e2eeeb9a913bd3ced8ac2
/usr/share/package-licenses/compose/c93b34f7b1daa3cce0988a6cc7140c9403de319d
/usr/share/package-licenses/compose/cd3e4d932cee20da681e6b3bee8139cb4f734034
/usr/share/package-licenses/compose/d22157abc0fc0b4ae96380c09528e23cf77290a9
/usr/share/package-licenses/compose/d2f340a01dd48b589a70f627cf7058c585a315e4
/usr/share/package-licenses/compose/d3b7a70b03b43d4e7205d178100581923a0baad2
/usr/share/package-licenses/compose/d3d30f733d36ea721eb89e9c37f899f729a0ea5e
/usr/share/package-licenses/compose/d676a57141ac47c27699fc8b03e1a2e59abb96ef
/usr/share/package-licenses/compose/d6a5f1ecaedd723c325a2063375b3517e808a2b5
/usr/share/package-licenses/compose/da34754c05d40ff81f91de8c1b85ea6e5503e21d
/usr/share/package-licenses/compose/dc2d3356b48d68245a75cc2dcbfd1881d413920f
/usr/share/package-licenses/compose/de6aabbb551ff752e690d7a1136a5b5228f130cb
/usr/share/package-licenses/compose/eecfc0c7e0930c6ba1ed0ff2d46a0a6fa0d16d6c
/usr/share/package-licenses/compose/f3a0255a9eb8e1668b0f178781487e9537df3071
/usr/share/package-licenses/compose/f3eab54cb1736b419ef75b8c44bea2b17614bd31
/usr/share/package-licenses/compose/f60d047cd34de4c91b3a045ebf117fe54b3c279e
/usr/share/package-licenses/compose/f7f33fde14de785a3ac53f250bb746ba30844639
/usr/share/package-licenses/compose/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca
